[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.2.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "v3.3.10"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v10.0.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.3"

[[constraint]]
  name = "github.com/containership/cluster-manager"
  version = "v5.0.1"

[[constraint]]
  name = "github.com/containership/csctl"
  revision = "8dac9bd6b4f418bb97b0d16ecbf3b420882078d6"

[[constraint]]
  name = "k8s.io/klog"
  version = "0.2.0"

[prune]
  go-tests = true
  unused-packages = true
